dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11

before_script: 
    -   cd L4B
    -   cd Lab4
script: ant build

notifications:
  email: cristian.nitu85@gmail.com
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bug;'